### ISSUE TITLE
How can we use the webcam?

### ISSUE THREAD

**Issue by lcristianiim** [IonicaBizau/image-to-ascii#14]
Can a webcam usage example be provided?
This is a very cool module!
Thanks!

**Comment by IonicaBizau** [comment]
It's already there, in the `test` directory. You should:

 1. Change `octocat.png` into `out.jpeg`
 2. Run `sh webcam.sh`

:smile:

**Comment by IonicaBizau** [comment]
However, we should add a more clearer example. Contributions are welcome! :four_leaf_clover:
