### ISSUE TITLE
Expose original character / rgb values as generated

### ISSUE THREAD

**Issue by Craigmoore** [IonicaBizau/image-to-ascii#17]
The values returned are perfect for consuming within a console, however for my project I needed the original character and rgb as generated.

Perhaps add a "pure data mode" boolean to the options and if so, add to an array structure instead of converting to final console string.

(Feature request)

**Comment by IonicaBizau** [comment]
@Craigmoore This is now covered in #25. Check it out. :smile:

**Comment by Craigmoore** [comment]
Looks insanely sweet, when I get some time to do some more node.js I will take a look - definately better than my hacky solution!

**Comment by IonicaBizau** [comment]
@Craigmoore A good example is [this one](https://github.com/IonicaBizau/image-to-ascii/blob/190e80dbcb1302a86fade40f02af6d4ed2c357fb/example/text-on-the-image.js). It modifies the characters before stringifying the things. :smile: 

:ship: `3.0.0` :tada:
