### ISSUE TITLE
CLI tool for this module

### ISSUE THREAD

**Issue by egoist** [IonicaBizau/image-to-ascii#27]
Hey Ionica,

I'm super happy now I got a chance to use this module, so I wonder if there is anything like `image-to-ascii-cli` exists. Otherwise maybe we can create one to use it directly via CLI   😂

**Comment by IonicaBizau** [comment]
@egoist Thanks for this! :sparkles: I do have a working version on my disk, but it's not yet published. :grin: But it's coming!

**Comment by egoist** [comment]
Thanks!

**Comment by IonicaBizau** [comment]
@egoist I published the cli tool here: https://github.com/IonicaBizau/image-to-ascii-cli

It's not providing a lot of options, but feel free to contribute. It's exactly the piece of code I wrote about one year ago when traveling with the train. Today I just initialized the git repo and open-sourced it. :grin: 

I'm trying to organize my stuff on my drive, so I upload ~~everything~~ lots of things on GitHub. :smile:
