### ISSUE TITLE
Difference between image-to-ascii and cli?

### ISSUE THREAD

**Issue by hansanghoon** [IonicaBizau/image-to-ascii#36]
![dsc08890](https://cloud.githubusercontent.com/assets/3644666/15772317/65884a74-29ab-11e6-8707-ba8403ace6f5.JPG)

Hi, I tried to convert above image using `image-to-ascii` and `image-to-ascii-cli`.

my code is as below.

```javascript
const imageToAscii = require("image-to-ascii");
const pxs = ".`:,;'_^\"\\></-!~=)(|j?}{ ][ti+l7v1%yrfcJ32uIC$zwo96sngaT5qpkYVOL40&mG8*xhedbZUSAQ
PFDXWK#RNEHBM@";

imageToAscii("DSC08890.JPG",
  {pixels:pxs},
  (err, converted) => { console.log(err || converted); }
);
```

results are

![screen shot 2016-06-03 at 4 49 15 pm](https://cloud.githubusercontent.com/assets/3644666/15772273/27fa1610-29ab-11e6-9e2f-23d65ae0ee5d.png)

Would you let me know how can I produce ascii image like `image-to-ascii-cli` using `image-to-ascii`? What options do I need?
Thanks.

**Comment by IonicaBizau** [comment]
What terminal emulator are you using? It looks like the color support is not correctly detected, but you can enforce it by using: `node your-script.js --color=256` 

More info: https://github.com/chalk/supports-color#info

**Comment by IonicaBizau** [comment]
The cli is using an older version of the module. 🔥

**Comment by hansanghoon** [comment]
![screen shot 2016-06-03 at 5 06 13 pm](https://cloud.githubusercontent.com/assets/3644666/15772684/872b7bfe-29ad-11e6-81e8-b50d020b2c12.png)

`--color=256` works! My mac terminal profile says *Declare terminal as: ansi*

**Comment by IonicaBizau** [comment]
@hansanghoon Ah, change that to `xterm-256color`. You will get 256 colors. ✨

**Comment by hansanghoon** [comment]
Got it. Thanks for quick response to my question 👍  😄

**Comment by IonicaBizau** [comment]
Great! Have fun using this module! 😁
