### ISSUE TITLE
Ability to specify how many times each character from variable 'pixels' is used to draw ASCII image …

### ISSUE THREAD

**Issue by fooness** [IonicaBizau/image-to-ascii#41]
Dear community, I thought it would be an adorable feature to be able to specify the character specific amount/number/times, each character for drawing the ASCII image—as specified in the `pixels` variable—should be used for drawing the ASCII image. This would also be very interesting for image-to-ascii-cli.

Kindest regards and thank you in advance.

**Comment by IonicaBizau** [comment]
There is an example here which can be changed to get what you want: https://github.com/IonicaBizau/image-to-ascii/blob/a56e3e5f2bcd75c5f377c99c5e3241e5dbc3c72f/example/text-on-the-image.js#L15-L19

**Comment by fooness** [comment]
Thank you for this snippet! It seems, image-to-ascii-cli does not have stringify integrated yet, is that correct or am I overseeing something? Kindest regards!

**Comment by fooness** [comment]
So after a few hours of trying it seems I can’t figure that out. Help would be very welcome. Thank you!

**Comment by IonicaBizau** [comment]
Please ask such questions on Stackoverflow.
