### ISSUE TITLE
Size of Screen printed

### ISSUE THREAD

**Issue by keepthefaya** [IonicaBizau/image-to-ascii#45]
hi, nice job for this package !
can we adjust size of picture in console.log, my picture is so big ? 

THanks

**Comment by keepthefaya** [comment]
i dont understand how to use options :+1: 
size (Object): The size of the result image (ASCII art):
height (Number|String): The height value (default: "100%").
width (Number|String): The width value (default: computed value to keep aspect ratio).


can you give me an example ? thanks

**Comment by IonicaBizau** [comment]
Try this:

```js
imageToAscii("https://octodex.github.com/images/octofez.png", {
  size: {
     height: "50%"
  }
}, (err, converted) => {
    console.log(err || converted);
});
```

**Comment by keepthefaya** [comment]
thannks :)

**Comment by IonicaBizau** [comment]
😄

**Comment by flyweights** [comment]
good！
