### ISSUE TITLE
how to save the output for a later use (without the lib needs)

### ISSUE THREAD

**Issue by gino8080** [IonicaBizau/image-to-ascii#46]
I want to get the "source" string to use alone in a website console without the need to include the libraries

I can only get the ascy without colors, how to do that?

thank you

**Comment by IonicaBizau** [comment]
Pass `colored: false` to disable the colors. This will output the ASCII art, which will not contain special ANSI escape codes (used for colors).

**Comment by IonicaBizau** [comment]
(see the example)
