### ISSUE TITLE
Can't install on windows due to install bug in lwipify

### ISSUE THREAD

**Issue by reppners** [IonicaBizau/image-to-ascii#49]
https://github.com/IonicaBizau/lwipify/issues/9

Open as issue here to be a reminder to upgrade once the dependency releases a fix.

**Comment by IonicaBizau** [comment]
@reppners Can you confirm one more time it works here as well after your fix in `lwip2`? 😁

**Comment by reppners** [comment]
also working, thx for the super fast reaction! 🥇

**Comment by IonicaBizau** [comment]
Wow, great to hear! 🎉
