### ISSUE TITLE
Getting ascii escape codes for each color

### ISSUE THREAD

**Issue by TheLarkInn** [IonicaBizau/image-to-ascii#51]
I'm building an npm module that I'd like to display an image that I have processed into ASCII. However I don't want users to have to depend on any of the C/C++ image binaries. Is there a way this node module can produce the ASCII escape codes of the string so that I can print this to console manually stored.

**Comment by IonicaBizau** [comment]
Umm... I don't know any. If you do find something which is cross-platform, let me know. The best I used is `graphicsmagick`.

One way would be to download the graphicsmagick binaries when doing npm install, depending on the platform.
