### ISSUE TITLE
Stream version?

### ISSUE THREAD

**Issue by benwiley4000** [IonicaBizau/image-to-ascii#57]
Can this accept an image stream so images can be created on the fly? Maybe I missed something along the way.

**Comment by IonicaBizau** [comment]
I was thinking about a streaming interface, but I'm not sure how we should build it. How would you use the streaming interface?

**Comment by benwiley4000** [comment]
Hm, well I guess I'm picturing:
```js
imageStream
  .pipe(imageToAscii(options))
  .pipe(process.stdout);
```
Or some variation of that.

But the other thing that occurred to me is that `source` (to the normal version) should be either a string or a `Buffer` - that's actually probably more the question I really meant to ask. 😁

**Comment by IonicaBizau** [comment]
I guess in that case [`image-parser`](https://github.com/IonicaBizau/image-parser) should be changed to support streaming.

Contributions are welcome, but I think that will be a big change... I'm open to ideas.

**Comment by benwiley4000** [comment]
I see, thanks for the pointer! It would be very cool to be able to display arbitrary animations via terminal, similar to [this](https://lifehacker.com/373571/watch-star-wars-in-text-via-telnet).

**Comment by benwiley4000** [comment]
@IonicaBizau would it be such a big change to at least support Buffers?

**Comment by benwiley4000** [comment]
Looks like [lwipify](https://github.com/IonicaBizau/lwipify) already supports buffers - the readme just needs to be updated here?

**Comment by IonicaBizau** [comment]
Buffers are supported already but docs were out of date. Thanks for updating them in #58.

To support streams the effort would be too big, but if anyone has ideas in this direction, they can comment here. We can reopen this issue in that case.
