### ISSUE TITLE
256 colors

### ISSUE THREAD

**Issue by pm0u** [IonicaBizau/image-to-ascii#63]
It seems in my terminal, images only ever display with 16 colors, although my terminal is capable of 256.. Is this an issue with my terminal or a limitation of image-to-ascii? 256 color support would be amazing!

**Comment by IonicaBizau** [comment]
What is the operating system / terminal you are using?

**Comment by pm0u** [comment]
I'm am using Termite and archlinux. I can get you more specific version info if needed

**Comment by IonicaBizau** [comment]
Try setting the `FORCE_COLOR` env variable:

```sh
# 16 colors
FORCE_COLOR=1 node example

# 256 colors
FORCE_COLOR=2 node example

# 16M colors
FORCE_COLOR=3 node example
```
