### ISSUE TITLE
Broken due to lwip installation issues

### ISSUE THREAD

**Issue by oliversalzburg** [IonicaBizau/image-to-ascii#66]
Can't get lwip to install on Ubuntu, which makes this module unusable :( It says to install ImageMagick if lwip doesn't work. I installed ImageMagick, but that didn't have any impact on the installation of this module.

**Comment by IonicaBizau** [comment]
What's the output of `which gm`?

You may need to install `graphicsmagick` instead.

**Comment by oliversalzburg** [comment]
Not sure if this was my original issue, but it might have been related to this https://github.com/ohmyzsh/ohmyzsh/issues/1432
